add_lunch_combo sd_flo-userdebug
add_lunch_combo sd_flounder-userdebug
add_lunch_combo sd_grouper-userdebug
add_lunch_combo sd_hammerhead-userdebug
add_lunch_combo sd_mako-userdebug
add_lunch_combo sd_manta-userdebug
add_lunch_combo sd_shamu-userdebug

