# Deodex
add_lunch_combo aospal_flo-userdebug
add_lunch_combo aospal_grouper-userdebug
add_lunch_combo aospal_hammerhead-userdebug
add_lunch_combo aospal_mako-userdebug

# Odex
add_lunch_combo aospal_flo-user
add_lunch_combo aospal_grouper-user
add_lunch_combo aospal_hammerhead-user
add_lunch_combo aospal_mako-user
