ifneq ($(SD_TYPE),)
        ROM_NAME := $(ROM_VERSION_MAJOR).$(ROM_VERSION_MINOR)-$(SD_TYPE)
        SD_VERSION := $(SD_TYPE)-$(SD_VERSION_MAJOR).$(SD_VERSION_MINOR)-$(SD_VERSION_MAINTENANCE)
else
        ROM_NAME := $(ROM_VERSION_MAJOR).$(ROM_VERSION_MINOR)
        SD_VERSION := $(SD_VERSION_MAJOR).$(SD_VERSION_MINOR)-$(SD_VERSION_MAINTENANCE)
endif

export BUILD_DATE := $(shell date -u +%Y%m%d)
ifeq ($(TARGET_BUILD_VARIANT),user)
        export ODEX_BUILD := true
endif
export SD_BUILD_NAME := $(ROM_NAME)-$(BUILD_DATE)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.$(VENDOR).version=$(SD_VERSION) \
    ro.$(VENDOR).modversion=$(SD_BUILD_NAME)
