ifneq ($(AOSPAL_TYPE),)
        ROM_NAME := $(ROM_VERSION_MAJOR).$(ROM_VERSION_MINOR)-$(AOSPAL_TYPE)
        AOSPAL_VERSION := $(AOSPAL_TYPE)-$(AOSPAL_VERSION_MAJOR).$(AOSPAL_VERSION_MINOR)-$(AOSPAL_VERSION_MAINTENANCE)
else
        ROM_NAME := $(ROM_VERSION_MAJOR).$(ROM_VERSION_MINOR)
        AOSPAL_VERSION := $(AOSPAL_VERSION_MAJOR).$(AOSPAL_VERSION_MINOR)-$(AOSPAL_VERSION_MAINTENANCE)
endif

export BUILD_DATE := $(shell date -u +%Y%m%d)
ifeq ($(TARGET_BUILD_VARIANT),user)
        export ODEX_BUILD := true
endif
export AOSPAL_BUILD_NAME := $(ROM_NAME)-$(BUILD_DATE)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.$(VENDOR).version=$(AOSPAL_VERSION) \
    ro.$(VENDOR).modversion=$(AOSPAL_BUILD_NAME)
